/* Generated By:JavaCC: Do not edit this line. MyLanguageParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyLanguageParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int NUMBER_TYPE = 7;
  /** RegularExpression Id. */
  int LETTER_TYPE = 8;
  /** RegularExpression Id. */
  int SENTENCE_TYPE = 9;
  /** RegularExpression Id. */
  int LOGIC_TYPE = 10;
  /** RegularExpression Id. */
  int TRUE_VAL = 11;
  /** RegularExpression Id. */
  int FALSE_VAL = 12;
  /** RegularExpression Id. */
  int DO = 13;
  /** RegularExpression Id. */
  int LENGTH_FUNC = 14;
  /** RegularExpression Id. */
  int PUSH_FUNC = 15;
  /** RegularExpression Id. */
  int POP_FUNC = 16;
  /** RegularExpression Id. */
  int NEW = 17;
  /** RegularExpression Id. */
  int SET_FUNC = 18;
  /** RegularExpression Id. */
  int GET_FUNC = 19;
  /** RegularExpression Id. */
  int DISPLAY_CMD = 20;
  /** RegularExpression Id. */
  int DISPLAY_NL_CMD = 21;
  /** RegularExpression Id. */
  int INPUT_CMD = 22;
  /** RegularExpression Id. */
  int IF = 23;
  /** RegularExpression Id. */
  int ELSEIF = 24;
  /** RegularExpression Id. */
  int ELSE = 25;
  /** RegularExpression Id. */
  int LOOP = 26;
  /** RegularExpression Id. */
  int TILL = 27;
  /** RegularExpression Id. */
  int BREAK = 28;
  /** RegularExpression Id. */
  int CONTINUE = 29;
  /** RegularExpression Id. */
  int SWITCH = 30;
  /** RegularExpression Id. */
  int CASE = 31;
  /** RegularExpression Id. */
  int DEFAULT_KWD = 32;
  /** RegularExpression Id. */
  int PLUS = 33;
  /** RegularExpression Id. */
  int MINUS = 34;
  /** RegularExpression Id. */
  int MULTIPLY = 35;
  /** RegularExpression Id. */
  int DIVIDE = 36;
  /** RegularExpression Id. */
  int MODULUS = 37;
  /** RegularExpression Id. */
  int LPAREN = 38;
  /** RegularExpression Id. */
  int RPAREN = 39;
  /** RegularExpression Id. */
  int LBRACE = 40;
  /** RegularExpression Id. */
  int RBRACE = 41;
  /** RegularExpression Id. */
  int LBRACKET = 42;
  /** RegularExpression Id. */
  int RBRACKET = 43;
  /** RegularExpression Id. */
  int DOT = 44;
  /** RegularExpression Id. */
  int ASSIGN = 45;
  /** RegularExpression Id. */
  int PLUSEQ = 46;
  /** RegularExpression Id. */
  int MINUSEQ = 47;
  /** RegularExpression Id. */
  int MULTEQ = 48;
  /** RegularExpression Id. */
  int DIVEQ = 49;
  /** RegularExpression Id. */
  int MODEQ = 50;
  /** RegularExpression Id. */
  int COMMA = 51;
  /** RegularExpression Id. */
  int ID = 52;
  /** RegularExpression Id. */
  int NUMBER_LITERAL = 53;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 54;
  /** RegularExpression Id. */
  int STRING_LITERAL = 55;
  /** RegularExpression Id. */
  int GT = 56;
  /** RegularExpression Id. */
  int LT = 57;
  /** RegularExpression Id. */
  int GTE = 58;
  /** RegularExpression Id. */
  int LTE = 59;
  /** RegularExpression Id. */
  int EQ = 60;
  /** RegularExpression Id. */
  int NEQ = 61;
  /** RegularExpression Id. */
  int AND = 62;
  /** RegularExpression Id. */
  int OR = 63;
  /** RegularExpression Id. */
  int NOT = 64;
  /** RegularExpression Id. */
  int INCREMENT = 65;
  /** RegularExpression Id. */
  int DECREMENT = 66;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<NUMBER_TYPE>",
    "<LETTER_TYPE>",
    "<SENTENCE_TYPE>",
    "<LOGIC_TYPE>",
    "<TRUE_VAL>",
    "<FALSE_VAL>",
    "<DO>",
    "<LENGTH_FUNC>",
    "<PUSH_FUNC>",
    "<POP_FUNC>",
    "<NEW>",
    "<SET_FUNC>",
    "<GET_FUNC>",
    "<DISPLAY_CMD>",
    "<DISPLAY_NL_CMD>",
    "<INPUT_CMD>",
    "<IF>",
    "<ELSEIF>",
    "<ELSE>",
    "<LOOP>",
    "<TILL>",
    "<BREAK>",
    "<CONTINUE>",
    "<SWITCH>",
    "<CASE>",
    "<DEFAULT_KWD>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\",\"",
    "<ID>",
    "<NUMBER_LITERAL>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"++\"",
    "\"--\"",
  };

}
